### ISSUE TITLE
error when using 'guidedfilter2d_color'

### ISSUE THREAD

**Issue by coolbeam** [perrying/guided-filter-pytorch#1]
Thanks for the author to share this code. But I meet some error here, when I run this demo:

> 

```        im = torch.randn((2, 3, 10, 10))
        target = torch.randn((2, 1, 10, 10))
        net = GuidedFilter2d(radius=4, eps=1e-4)
        res = net(target, im)
        print(res.shape)
```
I got the error information as below:
```
Traceback (most recent call last):
  File "/projects/guided-filter-pytorch-master/guided-filter-pytorch-master/guided_filter.py", line 204, in <module>
    demo()
  File "/projects/guided-filter-pytorch-master/guided-filter-pytorch-master/guided_filter.py", line 187, in demo
    res = net(target, im)
  File "D:\anaconda3.5.0.0\envs\torch1\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/projects/guided-filter-pytorch-master/guided-filter-pytorch-master/guided_filter.py", line 17, in forward
    return guidedfilter2d_color(guide, x, self.r, self.eps)
  File "/projects/guided-filter-pytorch-master/guided-filter-pytorch-master/guided_filter.py", line 117, in guidedfilter2d_color
    mean_a = torch.stack([boxfilter2d(a[:, i], radius) for i in range(3)], 1) / N
RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1
```
But there is no problem when I change the image to gray and run this code.  So I'm now running the gray version of this code. All in all, thank you very much for the sharing the code

**Comment by perrying** [comment]
The shape of N is incorrect.
I fixed it.
